import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        padding: 15,
        backgroundColor: '#f5f5f5',
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#e3f2fd',
        borderRadius: 10,
        padding: 15,
        marginBottom: 15,
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#003366',
    },
    statLabel: {
        fontSize: 12,
        color: '#666',
        marginTop: 4,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 10,
        paddingHorizontal: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    searchInput: {
        flex: 1,
        height: 45,
        color: '#333',
    },
    searchIcon: {
        marginLeft: 10,
    },
    dateFilterContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    dateFilterButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 10,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#ddd',
        flex: 1,
    },
    dateFilterText: {
        marginLeft: 8,
        color: '#003366',
    },
    clearDateFilterButton: {
        marginLeft: 10,
        padding: 10,
    },
    dateHeader: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#003366',
        marginVertical: 10,
        marginLeft: 5,
        backgroundColor: '#f5f5f5',
        padding: 5,
        borderRadius: 5,
    },
    filterContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    filterButton: {
        flex: 1,
        padding: 10,
        marginHorizontal: 2,
        backgroundColor: '#e0e0e0',
        borderRadius: 5,
        alignItems: 'center',
    },
    activeFilter: {
        backgroundColor: '#003366',
    },
    filterText: {
        color: '#333',
        fontWeight: 'bold',
        fontSize: 12,
    },
    activeFilterText: {
        color: 'white',
    },
    assistanceFilterContainer: {
        marginBottom: 15,
    },
    filterLabel: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#003366',
        marginBottom: 8,
    },
    assistanceFilterList: {
        paddingHorizontal: 5,
    },
    assistanceFilterButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        backgroundColor: '#e0e0e0',
        marginRight: 8,
    },
    activeAssistanceFilter: {
        backgroundColor: '#003366',
    },
    assistanceFilterText: {
        fontSize: 12,
        color: '#333',
    },
    activeAssistanceFilterText: {
        color: 'white',
    },
    selectionInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#e3f2fd',
        padding: 10,
        borderRadius: 5,
        marginBottom: 15,
    },
    selectionText: {
        color: '#003366',
        fontWeight: 'bold',
    },
    clearSelectionButton: {
        backgroundColor: '#f44336',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 5,
    },
    clearSelectionText: {
        color: 'white',
        fontSize: 12,
    },
    actionButton: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: '#003366',
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1,
        elevation: 5,
    },
    exportButton: {
        position: 'absolute',
        bottom: 6,
        left: 20,
        backgroundColor: '#4CAF50',
        padding: 15,
        borderRadius: 30,
        flexDirection: 'row',
        alignItems: 'center',
        zIndex: 1,
        elevation: 5,
    },
    exportButtonText: {
        color: 'white',
        fontWeight: 'bold',
        marginLeft: 5,
    },
    applicationCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        padding: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    selectedCard: {
        borderWidth: 2,
        borderColor: '#4CAF50',
        position: 'relative',
    },
    selectedOverlay: {
        position: 'absolute',
        top: 5,
        right: 5,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    applicationTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#003366',
        marginLeft: 8,
        flex: 1,
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 15,
    },
    statusText: {
        color: 'white',
        fontSize: 12,
        fontWeight: 'bold',
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    detailText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
        flex: 1,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    timeAgo: {
        fontSize: 12,
        color: '#999',
    },
    costText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#2196F3',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyText: {
        color: '#666',
        fontSize: 16,
        marginTop: 16,
        fontWeight: '500',
    },
    emptySubtext: {
        fontSize: 14,
        color: '#999',
        marginTop: 8,
        textAlign: 'center',
    },
    emptyListContainer: {
        flex: 1,
        justifyContent: 'center',
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalView: {
        width: '90%',
        maxWidth: 400,
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 5,
        color: '#003366',
    },
    modalSubtitle: {
        fontSize: 14,
        color: '#666',
        marginBottom: 20,
    },
    textInput: {
        width: '100%',
        borderColor: '#ddd',
        borderWidth: 1,
        borderRadius: 5,
        padding: 12,
        marginBottom: 20,
        backgroundColor: '#fff',
    },
    modalButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        padding: 12,
        borderRadius: 5,
        marginVertical: 5,
    },
    buttonRow: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
    },
    approveButton: {
        backgroundColor: '#4CAF50',
    },
    rejectButton: {
        backgroundColor: '#F44336',
    },
    updateButton: {
        backgroundColor: '#FF9800',
    },
    exportButtonModal: {
        backgroundColor: '#2196F3',
    },
    cancelButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#003366',
    },
    modalButtonText: {
        color: 'white',
        fontWeight: 'bold',
        marginLeft: 10,
    },
    loader: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    }
});