import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    tabContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    tabButton: {
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderBottomWidth: 3,
        borderBottomColor: 'transparent',
        position: 'relative',
    },
    activeTabButton: {
        borderBottomColor: '#003366',
    },
    tabButtonText: {
        color: '#666',
        fontWeight: '500',
        fontSize: 15,
    },
    activeTabButtonText: {
        color: '#003366',
        fontWeight: '600',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
    },
    loadingText: {
        marginTop: 10,
        color: '#003366',
        fontSize: 16,
    },
    filterBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 15,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    filterButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    leftFilters: {
        flexDirection: 'row',
        gap: 10,
    },
    rightFilters: {
        flexDirection: 'row',
        gap: 10,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        minWidth: 200,
    },
    activeSearchContainer: {
        backgroundColor: '#003366',
        borderColor: '#003366',
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        color: '#333',
        padding: 0,
    },
    activeSearchInput: {
        color: '#fff',
    },
    clearSearchButton: {
        padding: 4,
        marginLeft: 8,
    },
    filterButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        backgroundColor: '#f0f0f0',
        borderWidth: 1,
        borderColor: 'transparent',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
        transform: [{ scale: 1 }],
    },
    activeFilterButton: {
        backgroundColor: '#003366',
        borderColor: '#002244',
        transform: [{ scale: 1.02 }],
    },
    filterButtonText: {
        marginLeft: 8,
        color: '#003366',
        fontWeight: '500',
        fontSize: 14,
    },
    activeFilterButtonText: {
        color: '#fff',
    },
    clearFilterButton: {
        marginLeft: 8,
        padding: 4,
        borderRadius: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    kanbanContainer: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    kanbanColumn: {
        width: 320,
        backgroundColor: '#fff',
        borderRadius: 16,
        marginHorizontal: 8,
        marginVertical: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        flex: 1,
        overflow: 'hidden',
    },
    columnHeader: {
        padding: 16,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    columnTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 4,
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    columnDescription: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.95)',
        marginBottom: 4,
        maxWidth: 200,
        lineHeight: 18,
    },
    columnCountContainer: {
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.15)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    columnCount: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    columnCountSubtext: {
        fontSize: 11,
        color: 'rgba(255, 255, 255, 0.9)',
        marginTop: 2,
    },
    columnContent: {
        padding: 8,
    },
    columnContentContainer: {
        paddingBottom: 16,
    },
    emptyColumnContainer: {
        padding: 24,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.02)',
        borderRadius: 16,
        margin: 8,
        minHeight: 120,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.05)',
    },
    emptyColumnIcon: {
        marginBottom: 12,
        opacity: 0.5,
    },
    emptyColumnText: {
        color: '#666',
        fontSize: 14,
        textAlign: 'center',
        fontStyle: 'italic',
        lineHeight: 20,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    filterModalContent: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 24,
        width: '90%',
        maxWidth: 400,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    filterModalTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2c3e50',
        marginBottom: 8,
        textAlign: 'center',
    },
    filterModalSubtitle: {
        fontSize: 16,
        color: '#7f8c8d',
        marginBottom: 24,
        textAlign: 'center',
    },
    filterOptionsContainer: {
        marginBottom: 24,
    },
    filterOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        backgroundColor: '#f8f9fa',
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    selectedFilterOption: {
        backgroundColor: '#e3f2fd',
        borderColor: '#90caf9',
    },
    typeIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    filterOptionText: {
        fontSize: 16,
        color: '#2c3e50',
        flex: 1,
    },
    selectedFilterOptionText: {
        color: '#1976d2',
        fontWeight: '600',
    },
    modalCloseButton: {
        backgroundColor: '#1976d2',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    modalCloseButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    modalContent: {
        width: '90%',
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
    },
    modalButtonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    modalButton: {
        flex: 1,
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    cancelButton: {
        backgroundColor: '#6c757d',
    },
    confirmButton: {
        backgroundColor: '#003366',
    },
    modalButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    statusOption: {
        padding: 16,
        borderRadius: 12,
        marginVertical: 6,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    statusOptionText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    blockedDatesContainer: {
        flex: 1,
        padding: 16,
        backgroundColor: '#f8f9fa',
    },
    addBlockedDateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#dc3545',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    addBlockedDateButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        marginLeft: 8,
    },
    blockedDatesList: {
        paddingBottom: 20,
    },
    reasonInput: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        fontSize: 16,
        backgroundColor: '#f8f9fa',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalCloseIcon: {
        padding: 8,
    },
    searchModalContainer: {
        marginBottom: 20,
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        marginBottom: 16,
    },
    modalSearchInput: {
        flex: 1,
        fontSize: 16,
        color: '#333',
        marginLeft: 8,
        padding: 0,
    },
    searchResultsContainer: {
        maxHeight: 300,
    },
    searchResultItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    searchResultName: {
        fontSize: 16,
        color: '#333',
        marginBottom: 4,
    },
    searchResultType: {
        fontSize: 14,
        color: '#666',
    },
}); 