import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F9FAFB",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingTop: 15,
        paddingBottom: 10,
        backgroundColor: "#FFFFFF",
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
    },
    backIcon: {
        padding: 8,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#1E3A8A",
        marginLeft: 10,
    },
    progressContainer: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-end",
    },
    progressBar: {
        height: 8,
        width: 100,
        backgroundColor: "#E5E7EB",
        borderRadius: 4,
        marginRight: 8,
        overflow: "hidden",
    },
    progressFill: {
        height: "100%",
        backgroundColor: "#1E3A8A",
        borderRadius: 4,
    },
    progressText: {
        fontSize: 14,
        fontWeight: "500",
        color: "#4B5563",
    },
    scrollContainer: {
        padding: 20,
        paddingBottom: 100,
    },
    title: {
        fontSize: 24,
        fontWeight: "700",
        color: "#1E3A8A",
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 16,
        color: "#6B7280",
        marginBottom: 24,
    },
    inputContainer: {
        marginBottom: 20,
    },
    label: {
        fontSize: 16,
        fontWeight: "500",
        color: "#4B5563",
        marginBottom: 8,
    },
    optionalText: {
        fontSize: 14,
        color: "#9CA3AF",
        fontWeight: "400",
    },
    input: {
        backgroundColor: "#FFFFFF",
    },
    errorText: {
        fontSize: 12,
        color: "#EF4444",
        marginTop: 4,
    },
    datePickerButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderWidth: 1,
        borderColor: "#D1D5DB",
        borderRadius: 4,
        padding: 12,
    },
    datePickerButtonText: {
        flex: 1,
        fontSize: 16,
        color: "#1F2937",
        marginLeft: 10,
    },
    genderContainer: {
        flexDirection: "column",
        gap: 10,
    },
    genderOption: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "#FFFFFF",
        borderWidth: 1,
        borderColor: "#D1D5DB",
        borderRadius: 8,
        padding: 12,
    },
    genderSelected: {
        borderColor: "#1E3A8A",
        backgroundColor: "#EFF6FF",
    },
    radioWrapper: {
        flexDirection: "row",
        alignItems: "center",
    },
    genderText: {
        fontSize: 16,
        color: "#4B5563",
        marginLeft: 8,
    },
    genderTextSelected: {
        color: "#1E3A8A",
        fontWeight: "500",
    },
    genderIcon: {
        marginLeft: 10,
    },
    barangayContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
    },
    barangayOption: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        backgroundColor: "#FFFFFF",
        borderWidth: 1,
        borderColor: "#D1D5DB",
        borderRadius: 20,
    },
    barangaySelected: {
        borderColor: "#1E3A8A",
        backgroundColor: "#EFF6FF",
    },
    barangayText: {
        fontSize: 14,
        color: "#4B5563",
    },
    barangayTextSelected: {
        color: "#1E3A8A",
        fontWeight: "500",
    },
    privacyContainer: {
        marginTop: 20,
        marginBottom: 20,
        padding: 16,
        backgroundColor: "#F8FAFC",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#E2E8F0",
    },
    checkboxContainer: {
        flexDirection: "row",
        alignItems: "flex-start",
    },
    checkbox: {
        width: 22,
        height: 22,
        borderRadius: 4,
        borderWidth: 1.5,
        borderColor: "#9CA3AF",
        marginRight: 12,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 2,
    },
    checkboxChecked: {
        backgroundColor: "#1E3A8A",
        borderColor: "#1E3A8A",
    },
    privacyText: {
        flex: 1,
        fontSize: 14,
        color: "#4B5563",
        lineHeight: 20,
    },
    privacyLink: {
        color: "#1E40AF",
        fontWeight: "600",
        textDecorationLine: "underline",
    },
    bottomActions: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: "row",
        padding: 16,
        backgroundColor: "#FFFFFF",
        borderTopWidth: 1,
        borderTopColor: "#E5E7EB",
    },
    backButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: "#D1D5DB",
        borderRadius: 8,
        marginRight: 12,
    },
    backButtonText: {
        color: "#374151",
        fontWeight: "500",
        marginLeft: 8,
    },
    nextButton: {
        flex: 1,
        borderRadius: 8,
        overflow: "hidden",
    },
    nextButtonFull: {
        flex: 1,
    },
    gradientButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 14,
    },
    nextButtonText: {
        color: "#FFFFFF",
        fontWeight: "600",
        fontSize: 16,
        marginRight: 8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "flex-end",
    },
    modalContainer: {
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        paddingBottom: 30,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#1F2937",
    },
    datePickerContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 20,
    },
    dateColumn: {
        flex: 1,
        marginHorizontal: 5,
    },
    dateColumnHeader: {
        textAlign: "center",
        fontSize: 14,
        color: "#6B7280",
        marginBottom: 10,
        fontWeight: "500",
    },
    dateScrollView: {
        height: 200,
    },
    dateScrollContent: {
        paddingVertical: 10,
    },
    dateItem: {
        paddingVertical: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    dateItemSelected: {
        backgroundColor: "#EFF6FF",
        borderRadius: 8,
    },
    dateItemText: {
        fontSize: 16,
        color: "#4B5563",
    },
    dateItemTextSelected: {
        color: "#1E3A8A",
        fontWeight: "600",
    },
    modalFooter: {
        flexDirection: "row",
        justifyContent: "flex-end",
        marginTop: 10,
    },
    cancelButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: "#D1D5DB",
        borderRadius: 8,
        marginRight: 12,
    },
    cancelButtonText: {
        color: "#374151",
        fontWeight: "500",
    },
    confirmButton: {
        backgroundColor: "#1E3A8A",
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
    },
    confirmButtonText: {
        color: "#FFFFFF",
        fontWeight: "500",
    },
    // Privacy Policy Modal Styles
    privacyModalContainer: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    privacyModalContent: {
        backgroundColor: "white",
        borderRadius: 10,
        maxHeight: "80%",
        width: "90%",
        maxWidth: 500,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    privacyModalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
    },
    privacyModalTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#1E3A8A",
        flexShrink: 1,
    },
    privacyScrollView: {
        paddingHorizontal: 16,
    },
    privacyIntroText: {
        fontSize: 14,
        color: "#4B5563",
        marginBottom: 16,
        lineHeight: 20,
    },
    privacySectionTitle: {
        fontSize: 16,
        fontWeight: "600",
        color: "#1E3A8A",
        marginTop: 16,
        marginBottom: 8,
    },
    privacyCloseButton: {
        backgroundColor: "#1E3A8A",
        padding: 14,
        margin: 16,
        borderRadius: 8,
        alignItems: "center",
    },
    privacyCloseButtonText: {
        color: "white",
        fontWeight: "600",
        fontSize: 16,
    },
});

export default styles;